---
- name: create /var/run/sshd
  become: yes
  become_user: root
  with_items:
    - /var/run/sshd
    - '{{sshd_supervisord_profile_d}}'
  file:
    path: '{{item}}'
    state: directory
    mode: 0755

- name: install boot drop-in for initializing the sshd keys
  become: yes
  become_user: root
  with_items:
    - f: sshd-keycheck.sh
    - f: ssh-keyauth.sh
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d|default(sshd_supervisord_profile_d)}}/{{item.f}}'
    mode: '{{item.m|default("0755")}}'
